#include <array>
#include <multiaddr.h>
#include <varint.h>

static constexpr std::array protocols = {
    multiaddr::Protocol{4, 32, "ip4"},
    multiaddr::Protocol{6, 16, "tcp"},
    multiaddr::Protocol{273, 16, "udp"},
    multiaddr::Protocol{33, 16, "dccp"},
    multiaddr::Protocol{41, 128, "ip6"},
    multiaddr::Protocol{42, -1, "ip6zone"},
    multiaddr::Protocol{43, 8, "ipcidr"},
    multiaddr::Protocol{53, -1, "dns"},
    multiaddr::Protocol{54, -1, "dns4"},
    multiaddr::Protocol{55, -1, "dns6"},
    multiaddr::Protocol{56, -1, "dnsaddr"},
    multiaddr::Protocol{132, 16, "sctp"},
    multiaddr::Protocol{301, 0, "udt"},
    multiaddr::Protocol{302, 0, "utp"},
    multiaddr::Protocol{400, -1, "unix"},
    multiaddr::Protocol{421, -1, "p2p"},
    multiaddr::Protocol{421, -1, "ipfs"},
    multiaddr::Protocol{444, 96, "onion"},
    multiaddr::Protocol{445, 296, "onion3"},
    multiaddr::Protocol{446, -1, "garlic64"},
    multiaddr::Protocol{447, -1, "garlic32"},
    multiaddr::Protocol{448, 0, "tls"},
    multiaddr::Protocol{449, -1, "sni"},
    multiaddr::Protocol{454, 0, "noise"},
    multiaddr::Protocol{460, 0, "quic"},
    multiaddr::Protocol{461, 0, "quic-v1"},
    multiaddr::Protocol{465, 0, "webtransport"},
    multiaddr::Protocol{466, -1, "certhash"},
    multiaddr::Protocol{480, 0, "http"},
    multiaddr::Protocol{481, -1, "http-path"},
    multiaddr::Protocol{443, 0, "https"},
    multiaddr::Protocol{477, 0, "ws"},
    multiaddr::Protocol{478, 0, "wss"},
    multiaddr::Protocol{479, 0, "p2p-websocket-star"},
    multiaddr::Protocol{277, 0, "p2p-stardust"},
    multiaddr::Protocol{275, 0, "p2p-webrtc-star"},
    multiaddr::Protocol{276, 0, "p2p-webrtc-direct"},
    multiaddr::Protocol{280, 0, "webrtc-direct"},
    multiaddr::Protocol{281, 0, "webrtc"},
    multiaddr::Protocol{290, 0, "p2p-circuit"},
    multiaddr::Protocol{777, -1, "memory"}
};